def gv

pipeline{
    agent any
    // environment {
    //   NEW_VERSION='1.3.0'
    //   SERVER_CREDENTIALS=credentials('server-credentioals')
    // }
    parameters {
      //  string(name: 'VERSION', defaultValue: '', description: 'version to deploy on pord')
       choice(name:  'VERSION', choices:['1.1.0', '1.2.0', '1.3.0'], description: '')
       booleanParam(name: 'executeTests', defaultValue: true, description: '' )
    }
    stages{
        stage("init"){
          steps {
            script {
              gv = load "script.groovy"
            }
          }
        }
        stage("Build"){
            // when {
            //   expression {
            //     BRANCH_NAME == 'dev' && CODE_CHANGES == true
            //   }
            // }
            steps{
                // echo "========executing Build======"
                script {
                   gv.buildApp()
                }
            }
        }
        stage("test"){
            steps{
              when {
                expresseion {
                  params.executeTests
                }
              }
                // echo "========executing test========"
                script {
                  gv.testApp() 
                }
            }
        }
        stage("deploy"){
            steps{
                echo "========executing deploy========"
                script {
                   gv.deployApp()
                }
                // echo "deploy with ${SERVER_CREDENTIALS} "
                // withCredentials([
                //   usernamePassword('server-credentials', usernameVariable: USER, usernamePassword: PWD )
                // ]){
                //   sh "some script ${USER} and ${PWD}"
                // }

                // echo 'deploying version ${params.VERSION}'
            }
        }
    }
}